default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  host:     localhost
  username: postgres
  password:
  database: seeker_development

test:
  <<: *default
  host:     localhost
  username: postgres
  password:
  database: seeker_test

production:
  url: <%= ENV['DATABASE_URL'] %>
